#!/usr/bin/env python3
from enum import Enum
 
 
class FailureCode(str, Enum):
    WRAPPER_MISSING_CAST_REF = "WRAPPER_MISSING_CAST_REF"
    WRAPPER_MISSING_PLAYER = "WRAPPER_MISSING_PLAYER"
    WRAPPER_MISSING_JS = "WRAPPER_MISSING_JS"
    WRAPPER_MISSING_CSS = "WRAPPER_MISSING_CSS"
    NO_CAST_FILES_FOUND = "NO_CAST_FILES_FOUND"
    CAST_MISSING_WRAPPER = "CAST_MISSING_WRAPPER"
    WRAPPER_UNREADABLE = "WRAPPER_UNREADABLE"
    WRAPPER_DUPLICATE_PLAYER_BLOCK = "WRAPPER_DUPLICATE_PLAYER_BLOCK"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
    MISSING_RELATION = "MISSING_RELATION"
